# Generated by Django 4.0.3 on 2022-03-09 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
