# Generated by Django 4.0.3 on 2022-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0002_currency_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='description',
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=5, verbose_name='Currency'),
        ),
    ]
