# Generated by Django 4.0.3 on 2022-03-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0003_remove_currency_description_alter_currency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
