# Generated by Django 4.0.3 on 2022-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0004_currency_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='success',
        ),
        migrations.AddField(
            model_name='currency',
            name='rates',
            field=models.CharField(default='', max_length=200, verbose_name='Rates'),
            preserve_default=False,
        ),
    ]
