# Generated by Django 4.0.3 on 2022-03-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0005_remove_currency_success_currency_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rates',
            field=models.TextField(verbose_name='Rates'),
        ),
    ]
