# Generated by Django 4.0.3 on 2022-03-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0008_alter_currency_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rates',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=15),
        ),
    ]
