# Generated by Django 4.0.3 on 2022-03-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0009_alter_currency_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='mex',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rates',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
