# Generated by Django 4.0.3 on 2022-03-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0010_currency_mex_alter_currency_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='frc',
            field=models.FloatField(default=0),
        ),
    ]
