# Generated by Django 4.0.3 on 2022-03-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0011_currency_frc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='rates',
        ),
        migrations.AlterField(
            model_name='currency',
            name='mex',
            field=models.FloatField(default=0.0),
        ),
    ]
