# Generated by Django 4.0.3 on 2022-03-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0012_remove_currency_rates_alter_currency_mex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='frc',
            new_name='AUD',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='mex',
            new_name='CUD',
        ),
        migrations.AddField(
            model_name='currency',
            name='EUR',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='currency',
            name='MXN',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='currency',
            name='PLN',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='currency',
            name='USD',
            field=models.FloatField(default=0.0),
        ),
    ]
